
%% LilyPond file generated by Denemo version 2.0.0

%%http://www.gnu.org/software/denemo/

\version "2.18.0"

CompactChordSymbols = {}
#(define DenemoTransposeStep 0)
#(define DenemoTransposeAccidental 0)
DenemoGlobalTranspose = #(define-music-function (parser location arg)(ly:music?) #{\transpose c c #arg #})
titledPiece = {}
AutoBarline = {}
AutoEndMovementBarline = \bar "|."

       
#(define ((bars-per-line-engraver bar-list) context)
  (let* ((working-copy bar-list)
         (total (1+ (car working-copy))))
    `((acknowledgers
       (paper-column-interface
        . ,(lambda (engraver grob source-engraver)
             (let ((internal-bar (ly:context-property context 'internalBarNumber)))
               (if (and (pair? working-copy)
                        (= (remainder internal-bar total) 0)
                        (eq? #t (ly:grob-property grob 'non-musical)))
                   (begin
                     (set! (ly:grob-property grob 'line-break-permission) 'force)
                     (if (null? (cdr working-copy))
                         (set! working-copy bar-list)
                         (begin
                           (set! working-copy (cdr working-copy))))
                           (set! total (+ total (car working-copy))))))))))))
\layout {
   \context {
      \Score
      %use the line below to insist on your layout
      %\override NonMusicalPaperColumn.line-break-permission = ##f
      \consists #(bars-per-line-engraver '( 3))}}                             
                           #(define denemo-top-margin Op. 821. No.1)
\include "simplified-book-titling.ily"

% The music follows

MvmntIVoiceI = {
         <e''-3 >16 <g''-5 >16 f'' g'' <e''-3 >16 f'' <d''-2 >16 e'' <c''-1 >16 <c'''-5 >16 b'' c''' <a''-3 >16 b'' <g''-2 >16 a''\AutoBarline
         <f''-1 >16 <a''-5 >16 g'' a'' <f''-3 >16 g'' e'' f'' d'' <f''-5 >16 e'' f'' <d''-3 >16 e'' c'' d''\AutoBarline
         <b'-1 >16-\cresc <d''-5 >16 c'' d'' <b'-3 >16 c'' a' b' <g'-1 >16 <b'-5 >16 a' b' g' a' f' g'\AutoBarline
         <e'-1 >16 <g'-5 >16 f' g' e' f' d' e' <c'-1 >16 <e'-5 >16 d' e' c' d' b c'\AutoBarline
%5
        <>  \f <a-1 >16 <d'-3 >16 cis' <e'-4 >16 <d'-1 >16 f' e' <g'-4 >16 <f'-1 >16 a' gis' <b'-4 >16 <a'-1 >16 <d''-3 >16 cis'' <e''-4 >16\AutoBarline
         <d''-1 >16 f'' e'' <g''-4 >16 <f'> a' gis' <b'> \ottava #1  <a'>16 d'' cis'' <e''> <d''> e'' f'' d''\AutoBarline
         <a''> g'' f'' e'' \ottava #0  <d'''-1 >16 <c'''-3 >16 b'' a'' <g''-4 >16 f'' e'' d'' <c''-3 >16 b' a' b'\AutoBarline
         c'' d'' c'' b' <c''-1 >16 e'' g'' c''' c''8-\staccato r8 r4 \AutoEndMovementBarline
}


MvmntIVoiceII = {
         <c' g'>4 r <e' g'> r\AutoBarline
         <d' a'> r \clef bass <f a> r\AutoBarline
         <g d'> r <b, d g> r\AutoBarline
         <g, c> r <e g> r\AutoBarline
%5
         <f, a, d> r r2\AutoBarline
         <f a d'>4 r r2\AutoBarline
         <g c' e'>4 r <g d' f'> r\AutoBarline
         <c' e'> r r2 \AutoEndMovementBarline
}





%Default Score Layout
\header{DenemoLayoutName = "Default Score Layout"}

\header {
tagline = \markup {"/Users/mcasl/GoogleDrive/0-PRESENTE/PIANO/CZERNY/OP. 821 - 160 short studies Peters/Op-821-No-001.denemo" on \simple #(strftime "%x" (localtime (current-time)))}

        }
#(set-default-paper-size "a4")
#(set-global-staff-size 18)
\paper {

       }

\score { %Start of Movement
          <<
 \new PianoStaff << \set PianoStaff.instrumentName = #"Piano"  

%Start of Staff
\new Staff = "Piano"  << 
 \new Voice = "VoiceIMvmntI"  { 
  \clef treble    \key c \major    \time 4/4   \MvmntIVoiceI
                        } %End of voice

                        >> %End of Staff

%Start of Staff
\new Staff = "Piano"  << 
 \new Voice = "VoiceIIMvmntI"  { 
  \clef treble    \key c \major    \time 4/4   \MvmntIVoiceII
                        } %End of voice

                        >> %End of Staff
 >>%Brace End

          >>

       } %End of Movement

