\version "2.10.0"
mutopiatitle = "Eine kleine Nachtmusik (1st movement)"
mutopiacomposer = "MozartWA"
mutopiaopus = "KV 525"
mutopiainstrument = "Violin, Viola, Cello, Double Bass"
date = "1787"
source = "http://www.imslp.org/"
style = "Classical"
copyright = "Public Domain"
maintainer = "Anonymous"
maintainerEmail = "gnomino@hotmail.com"
lastupdated = "2006/Dec/31"
 footer = "Mutopia-2007/01/01-900"
 tagline = \markup { \override #'(box-padding . 1.0) \override #'(baseline-skip . 2.7) \box \center-align { \small \line { Sheet music from \with-url #"http://www.MutopiaProject.org" \line { \teeny www. \hspace #-1.0 MutopiaProject \hspace #-1.0 \teeny .org \hspace #0.5 } • \hspace #0.5 \italic Free to download, with the \italic freedom to distribute, modify and perform. } \line { \small \line { Typeset using \with-url #"http://www.LilyPond.org" \line { \teeny www. \hspace #-1.0 LilyPond \hspace #-1.0 \teeny .org } by \maintainer \hspace #-1.0 . \hspace #0.5 Reference: \footer } } \line { \teeny \line { This sheet music has been placed in the public domain by the typesetter, for details see: \hspace #-0.5 \with-url #"http://creativecommons.org/licenses/publicdomain" http://creativecommons.org/licenses/publicdomain } } } }
