\piecePartSpecs #`((violino1)
                   (violino2)
                   (viola)
                   (vocal)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi #:clef "treble"))