\piecePartSpecs #`((dessus1 #:notes "dessus1")
                   (dessus2 #:notes "dessus2")
                   (haute-contre)
                   (taille)
                   (basse #:score "score-basse")
                   (voix)
                   (basse-continue #:notes "basse-continue"))
