\version "2.18.0"
\header
{
  dedication = ""
  subtitle = ""
  subsubtitle = ""
  poet = ""
  instrument = "Guitar"
  meter = ""
  arranger = ""
  piece = ""
  opus = ""
  breakbefore = ##f
  license = "Creative Commons Attribution 4.0"
  source = "Guitar-Skole af A. Eggers, The Royal Library (Det Kongelige Bibliotek), Copenhagen, Denmark" 
  style = "Classical"
  maintainer = "Louie van Bommel"
  composer="Ferdinando Carulli"
  mutopiacomposer="CarulliF"
  title="Guitar-Skole no. 11 :  Tempo di Valse "
  footer = "Mutopia-2009/06/08-1665"
}
\include "generic-paper-section.ly"
\include "generic-layout-section.ly"
\include "guitar-skole-defines-section.ly"
\include "guitar-skole-music-11.ly"
\include "generic-score-section.ly"
