Glo -- ry to God,
glo -- ry to God in the high -- est,
Glo -- ry to God,
glo -- ry to God,
glo -- ry to God in the high -- est,
good will __ to -- wards men, to -- wards men,
good will __ to -- wards men, to -- wards men,
good will __ to -- wards men.
Glo -- ry to God,
glo -- ry to God in the high -- est,
and peace on earth,
good will __ to -- wards men, to -- wards men,
good will, good will, good will,
good will to -- wards men,
good will __ to -- wards men.