\piecePartSpecs #`((violino1)
                   (violino2)
                   (viola)
                   (vocal)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi #:score-template "score"))