\piecePartSpecs #`((tromba1 #:notes "tromba")
                   (tromba2 #:notes "tromba")
                   (violino1)
                   (violino2)
                   (viola)
                   (vocal)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi #:score-template "score"))