\piecePartSpecs #`((dessus1)
                   (dessus2)
                   (haute-contre)
                   (taille)
                   (quinte)
                   (basse)
                   (basse-continue #:score-template "score"))
