.phony: all

all: HWV370-violin.pdf HWV370-score.pdf
violin: HWV370-violin.pdf
score: HWV370-score.pdf

HWV370-violin.pdf: HWV370-violin.ly 
	lilypond $<

HWV370-score.pdf: HWV370-score.ly 
	lilypond $<
