\piecePartSpecs #`((dessus1)
                   (dessus2)
                   (haute-contre)
                   (taille)
                   (basse)
                   (voix)
                   (basse-continue #:score "score-basse-continue"))
