\includeNotes "dessus-a"
s4*0^"Hautbois" \includeNotes "dessus-b2"
s4*0^"Tous" \includeNotes "dessus-c"
s4*0^"Hautbois" \includeNotes "dessus-d2"
s4*0^"Tous" \includeNotes "dessus-e"
s4*0^"Hautbois" \includeNotes "dessus-f2"
s4*0^"Tous" \includeNotes "dessus-g"