cresc = \markup {\italic "cresc."}
div = \markup {\italic "div."}
uni = \markup {\italic "uni."}
arc = \markup {\italic "arco"}
decresc = \markup {\italic "decresc."}
dolce = \markup {\italic "dolce"}
pdolce = \markup{\dynamic "p" \italic " e dolce"}
piz = \markup { \italic "pizz."}
arc = \markup { \italic "arco"}
vl = \markup { \italic "Vcl."}
