\piecePartSpecs #`((violino1)
                   (violino2)
                   (oboe1 #:notes "oboe")
                   (oboe2 #:notes "oboe")
                   (viola)
                   (vocal)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi))