\piecePartSpecs #`((tromba1)
                   (tromba2)
                   (tympani)
                   (violino1)
                   (violino2)
                   (viola)
                   (vocal)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi))