
\include "english.ly"
\include "../defs.ily"
\include "../paper.ily"
\include "global.ily"

\include "flauti.ily"
\include "flauti2.ily"
\include "oboi.ily"
\include "clarinettiA.ily"
\include "fagotti.ily"
\include "corniF.ily"
\include "corniF2.ily"
\include "trombeD.ily"
\include "timpani.ily"
\include "solo.ily"
\include "violino1.ily"
\include "violino2.ily"
\include "viola.ily"
\include "violoncello.ily"
\include "contrabasso.ily"
