\piecePartSpecs #`((violino1)
                   (violino2)
                   (viola)
                   (vocal #:indent 0)
                   (vocal-keyboard #:indent 0)
                   (keyboard)
                   (bassi))