# Makefile.single_ly_landscape

all: $(addsuffix .rdf, $(basename $(wildcard *.ly))) \
     $(addsuffix .log, $(basename $(wildcard *.ly)))

%.rdf: %.ly
	mutopia-clean.sh
	Mutopia -f $<
	mutopia-compile.sh -l $<
	Mutopia -r $<

%.log: %.ly
	mutopia-history.sh
