\piecePartSpecs #`((violino1)
                   (violino2)
                   (oboe1)
                   (oboe2)
                   (viola)
                   (vocal)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi))