la, la, la, la, la, la, la, la, la, la, la, la, 
la, la, la, la, la, la, la, la, la, la, la, la, 
la, la, la, la, la, la, 
en ca -- den -- ce s'il vous plaît,
la, la, la, la, 
la jam -- be droi -- te,
la, la, la, 
ne re -- muez point tant les é -- pau -- les,
la, la, la, la, la, la, la, la, la, la,
vos deux bras sont es -- tro -- piés,
la, la, la, la, la,
haus -- sez la tê -- te,
tour -- nez la poin -- te du pied en de -- hors,
la, la, la,
dres -- sez vo -- tre corps.