.phony: all

all: HWV361-violin.pdf HWV361-score.pdf
violin: HWV361-violin.pdf
score: HWV361-score.pdf

HWV361-violin.pdf: HWV361-violin.ly 
	lilypond $<

HWV361-score.pdf: HWV361-score.ly 
	lilypond $<
