\piecePartSpecs #`((dessus1 #:notes "dessus1")
                   (dessus2 #:notes "dessus2")
                   (haute-contre)
                   (taille)
                   (quinte)
                   (basse)
                   (basse-continue #:notes "basse-continue"))
