\piecePartSpecs #`((violino1 #:notes "violini")
                   (violino2 #:notes "violini")
                   (vocal)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi))