\piecePartSpecs #`((dessus1)
                   (dessus2)
                   (haute-contre)
                   (taille)
                   (quinte)
                   (basse)
                   (voix)
                   (basse-continue))
