\piecePartSpecs #`((violino1 #:notes "violino12")
                   (violino2 #:notes "violino12")
                   (violino3 #:notes "violino3")
                   (viola)
                   (vocal)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi))