\version "2.18.2"

\header {
  title        = "Pictures at an Exhibition"
  composer     = "Modest Moussorgsky (1839 - 1881)"
  style        = "Romantic"
  license      = "Creative Commons Attribution-ShareAlike 4.0"
  enteredby    = "Knute Snortum" 
  date         = "1874"
  source       = "Pavel Lamm"
  lastupdated  = "14-Jul-2014"

  mutopiatitle       = "Pictures at an Exhibition"
  mutopiacomposer    = "MussorgskyM"
  mutopiainstrument  = "Piano"
  maintainer         = "Knute Snortum"
  maintainerEmail    = "knute (at) snortum (dot) net"
  maintainerWeb      = "http://www.musicwithknute.com/"
}

\include "promenade-1.ly"
\include "gnomus.ly"
\include "promenade-2.ly"
\include "il-vecchio-castello.ly"
\include "promenade-3.ly"
\include "tuileries.ly"
\include "bydlo.ly"
\include "promenade-4.ly"
\include "ballet.ly"
\include "two-jews.ly"
\include "promenade-5.ly"
\include "limoges.ly"
\include "catacombae.ly"
\include "promenade-6.ly"
\include "baba.ly"
\include "great-gate.ly"
