\piecePartSpecs #`((violino1)
                   (violino2)
                   (viola)
                   (oboe1 #:instrument "Oboe" #:notes "oboe1")
                   (oboe2 #:instrument "Oboe" #:notes "oboe2")
                   (vocal)
                   (vocal-keyboard)
                   (keyboard)
                   (bassi))