
a4:
	lilypond -b null -d write-tweaks -o out/giulio-cesare giulio-cesare.ly && \
	lilypond -o out/giulio-cesare giulio-cesare.ly 
letter:
	lilypond -b null -d write-tweaks -d letter -o out/giulio-cesare giulio-cesare.ly && \
	lilypond -d letter -o out/giulio-cesare giulio-cesare.ly 
.PHONY: a4
.PHONY: letter 
